<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="0" total="12" passed="12">
  <reporter-output>
  </reporter-output>
  <suite name="Command line suite" duration-ms="144" started-at="2018-07-30T16:17:44Z" finished-at="2018-07-30T16:17:44Z">
    <groups>
    </groups>
    <test name="Command line test" duration-ms="144" started-at="2018-07-30T16:17:44Z" finished-at="2018-07-30T16:17:44Z">
      <class name="MessageActionsTest">
        <test-method status="PASS" signature="testRandomMessageToPublic_WeightGreaterThan10Pow9_ShouldThrowException()[pri:0, instance:MessageActionsTest@d041cf]" name="testRandomMessageToPublic_WeightGreaterThan10Pow9_ShouldThrowException" duration-ms="13" started-at="2018-07-30T23:17:44Z" finished-at="2018-07-30T23:17:44Z">
          <exception class="java.lang.IllegalArgumentException">
            <message>
              <![CDATA[Weight should be 0 ≤ weightArray[i] ≤ 10^9]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.IllegalArgumentException: Weight should be 0 ≤ weightArray[i] ≤ 10^9
	at MessageActions.getWeightedRandomMessageToPublic(MessageActions.java:22)
	at MessageActionsTest.testRandomMessageToPublic_WeightGreaterThan10Pow9_ShouldThrowException(MessageActionsTest.java:52)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:77)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:159)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:99)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:106)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.IllegalArgumentException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testRandomMessageToPublic_WeightGreaterThan10Pow9_ShouldThrowException -->
        <test-method status="PASS" signature="testRandomMessageToPublic_WeightIs0_ShouldBePassed()[pri:0, instance:MessageActionsTest@d041cf]" name="testRandomMessageToPublic_WeightIs0_ShouldBePassed" duration-ms="4" started-at="2018-07-30T23:17:44Z" finished-at="2018-07-30T23:17:44Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testRandomMessageToPublic_WeightIs0_ShouldBePassed -->
        <test-method status="PASS" signature="testRandomMessageToPublic_WeightIs10Pow9_ShouldBePassed()[pri:0, instance:MessageActionsTest@d041cf]" name="testRandomMessageToPublic_WeightIs10Pow9_ShouldBePassed" duration-ms="1" started-at="2018-07-30T23:17:44Z" finished-at="2018-07-30T23:17:44Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testRandomMessageToPublic_WeightIs10Pow9_ShouldBePassed -->
        <test-method status="PASS" signature="testRandomMessageToPublic_WeightLessThan0_ShouldThrowException()[pri:0, instance:MessageActionsTest@d041cf]" name="testRandomMessageToPublic_WeightLessThan0_ShouldThrowException" duration-ms="3" started-at="2018-07-30T23:17:44Z" finished-at="2018-07-30T23:17:44Z">
          <exception class="java.lang.IllegalArgumentException">
            <message>
              <![CDATA[Weight should be 0 ≤ weightArray[i] ≤ 10^9]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.IllegalArgumentException: Weight should be 0 ≤ weightArray[i] ≤ 10^9
	at MessageActions.getWeightedRandomMessageToPublic(MessageActions.java:22)
	at MessageActionsTest.testRandomMessageToPublic_WeightLessThan0_ShouldThrowException(MessageActionsTest.java:67)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:77)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:159)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:99)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:106)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.IllegalArgumentException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testRandomMessageToPublic_WeightLessThan0_ShouldThrowException -->
        <test-method status="PASS" signature="testRandomMessageToPublic_WithN_GreaterThan100_ShouldThrowException()[pri:0, instance:MessageActionsTest@d041cf]" name="testRandomMessageToPublic_WithN_GreaterThan100_ShouldThrowException" duration-ms="21" started-at="2018-07-30T23:17:44Z" finished-at="2018-07-30T23:17:44Z">
          <exception class="java.lang.IllegalArgumentException">
            <message>
              <![CDATA[N should be 1 ≤ N ≤ 100]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.IllegalArgumentException: N should be 1 ≤ N ≤ 100
	at MessageActions.getWeightedRandomMessageToPublic(MessageActions.java:16)
	at MessageActionsTest.testRandomMessageToPublic_WithN_GreaterThan100_ShouldThrowException(MessageActionsTest.java:18)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:77)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:159)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:99)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:106)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.IllegalArgumentException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testRandomMessageToPublic_WithN_GreaterThan100_ShouldThrowException -->
        <test-method status="PASS" signature="testRandomMessageToPublic_WithN_LessThan1_ShouldThrowException()[pri:0, instance:MessageActionsTest@d041cf]" name="testRandomMessageToPublic_WithN_LessThan1_ShouldThrowException" duration-ms="0" started-at="2018-07-30T23:17:44Z" finished-at="2018-07-30T23:17:44Z">
          <exception class="java.lang.IllegalArgumentException">
            <message>
              <![CDATA[N should be 1 ≤ N ≤ 100]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.IllegalArgumentException: N should be 1 ≤ N ≤ 100
	at MessageActions.getWeightedRandomMessageToPublic(MessageActions.java:16)
	at MessageActionsTest.testRandomMessageToPublic_WithN_LessThan1_ShouldThrowException(MessageActionsTest.java:44)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:77)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:159)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:99)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:106)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.IllegalArgumentException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testRandomMessageToPublic_WithN_LessThan1_ShouldThrowException -->
        <test-method status="PASS" signature="testRandomMessageToPublic_WithN_is100_ShouldThrowException()[pri:0, instance:MessageActionsTest@d041cf]" name="testRandomMessageToPublic_WithN_is100_ShouldThrowException" duration-ms="1" started-at="2018-07-30T23:17:44Z" finished-at="2018-07-30T23:17:44Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testRandomMessageToPublic_WithN_is100_ShouldThrowException -->
        <test-method status="PASS" signature="testRandomMessageToPublic_WithN_is1_ShouldThrowException()[pri:0, instance:MessageActionsTest@d041cf]" name="testRandomMessageToPublic_WithN_is1_ShouldThrowException" duration-ms="2" started-at="2018-07-30T23:17:44Z" finished-at="2018-07-30T23:17:44Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testRandomMessageToPublic_WithN_is1_ShouldThrowException -->
      </class> <!-- MessageActionsTest -->
      <class name="utils.RandomizerTest">
        <test-method status="PASS" signature="TestRandomIntInRange_WithValidInput_ResultShouldBeInsideBounds()[pri:0, instance:utils.RandomizerTest@2f7c7260]" name="TestRandomIntInRange_WithValidInput_ResultShouldBeInsideBounds" duration-ms="0" started-at="2018-07-30T23:17:44Z" finished-at="2018-07-30T23:17:44Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TestRandomIntInRange_WithValidInput_ResultShouldBeInsideBounds -->
        <test-method status="PASS" signature="testGetWeightedRandomFromArray_WithValidData_ShouldBePassed()[pri:0, instance:utils.RandomizerTest@2f7c7260]" name="testGetWeightedRandomFromArray_WithValidData_ShouldBePassed" duration-ms="55" started-at="2018-07-30T23:17:44Z" finished-at="2018-07-30T23:17:44Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testGetWeightedRandomFromArray_WithValidData_ShouldBePassed -->
        <test-method status="PASS" signature="testRandomIntInRange_MinEqualToMax_ShouldThrowException()[pri:0, instance:utils.RandomizerTest@2f7c7260]" name="testRandomIntInRange_MinEqualToMax_ShouldThrowException" duration-ms="1" started-at="2018-07-30T23:17:44Z" finished-at="2018-07-30T23:17:44Z">
          <exception class="java.lang.IllegalArgumentException">
            <message>
              <![CDATA[max must be greater than min]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.IllegalArgumentException: max must be greater than min
	at utils.Radomizer.randomIntInRange(Radomizer.java:39)
	at utils.RandomizerTest.testRandomIntInRange_MinEqualToMax_ShouldThrowException(RandomizerTest.java:31)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:77)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:159)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:99)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:106)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.IllegalArgumentException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testRandomIntInRange_MinEqualToMax_ShouldThrowException -->
        <test-method status="PASS" signature="testRandomIntInRange_MinGreaterThanMax_ShouldThrowException()[pri:0, instance:utils.RandomizerTest@2f7c7260]" name="testRandomIntInRange_MinGreaterThanMax_ShouldThrowException" duration-ms="3" started-at="2018-07-30T23:17:44Z" finished-at="2018-07-30T23:17:44Z">
          <exception class="java.lang.IllegalArgumentException">
            <message>
              <![CDATA[max must be greater than min]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.IllegalArgumentException: max must be greater than min
	at utils.Radomizer.randomIntInRange(Radomizer.java:39)
	at utils.RandomizerTest.testRandomIntInRange_MinGreaterThanMax_ShouldThrowException(RandomizerTest.java:25)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:77)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:159)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:99)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:106)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.IllegalArgumentException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testRandomIntInRange_MinGreaterThanMax_ShouldThrowException -->
      </class> <!-- utils.RandomizerTest -->
    </test> <!-- Command line test -->
  </suite> <!-- Command line suite -->
</testng-results>
